import Head from 'next/head'
import Hero from '@/components/Hero';
import CartComponent from '@/components/CartComponent';


export default function Cart() {
  return (
    <>
      <Head>
        <title>DetoxFolks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Hero name='Cart' />

      <section className="inner-section checkout-part">
        <div className="container">
            <CartComponent is_page={true} />
        </div>
      </section>

    </>
  )
}
