import Head from 'next/head'
import ContactCard from '@/components/ContactCard';
import Hero from '@/components/Hero';
import Layout from '@/components/Layout';


export default function Contact() {
  return (
    <Layout>
        <Head>
            <title>Detox-Folks</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/images/favicon.png" />
        </Head>
        <Hero name='Contact Us' />

        <section className="inner-section contact-part">
            <div className="container">
                <div className="row">
                    <div className="col-md-6 col-lg-4">
                        <ContactCard icon='icofont-location-pin' active={false} heading='head office' description='1Hd- 50, 010 Avenue, NY 90001 United States' />
                    </div>
                    <div className="col-md-6 col-lg-4">
                        <ContactCard icon='icofont-phone' active={true} heading='phone number' description='009-215-5596' />
                    </div>
                    <div className="col-md-6 col-lg-4">
                        <ContactCard icon='icofont-email' active={false} heading='Support mail' description='contact@example.com' />
                    </div>
                </div>
                <div className="row">
                    <div className="col-lg-6">
                        <div className="contact-map"><iframe
                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3654.3406974350205!2d90.48469931445422!3d23.663771197998262!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755b0d5983f048d%3A0x754f30c82bcad3cd!2sJalkuri%20Bus%20Stop!5e0!3m2!1sen!2sbd!4v1605354966349!5m2!1sen!2sbd" aria-hidden="false" tabIndex={0}></iframe></div>
                    </div>
                    <div className="col-lg-6">
                        <form className="contact-form">
                            <h4>Drop Your Thoughts</h4>
                            <div className="form-group">
                                <div className="form-input-group"><input className="form-control" type="text"
                                        placeholder="Your Name" /><i className="icofont-user-alt-3"></i></div>
                            </div>
                            <div className="form-group">
                                <div className="form-input-group"><input className="form-control" type="text"
                                        placeholder="Your Email" /><i className="icofont-email"></i></div>
                            </div>
                            <div className="form-group">
                                <div className="form-input-group"><input className="form-control" type="text"
                                        placeholder="Your Subject" /><i className="icofont-book-mark"></i></div>
                            </div>
                            <div className="form-group">
                                <div className="form-input-group"><textarea className="form-control"
                                        placeholder="Your Message"></textarea><i className="icofont-paragraph"></i></div>
                            </div><button type="submit" className="form-btn-group"><i className="fas fa-envelope"></i><span>send
                                    message</span></button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    
    </Layout>
  )
}
