import Head from 'next/head'
import Link from 'next/link'
import * as yup from "yup";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import { useState } from 'react';
import { axiosPublic } from '../../axios';
import { api_routes } from '@/helper/routes';
import { ErrorMessage } from '@hookform/error-message';
import { ToastOptions, toast } from 'react-toastify';
import Spinner from '@/components/Spinner';


const schema = yup
  .object({
    email: yup.string().email().required(),
  })
  .required();

const toastConfig:ToastOptions = {
    position: "bottom-center",
    autoClose: 5000,
    hideProgressBar: false,
    closeOnClick: true,
    pauseOnHover: true,
    draggable: true,
    progress: undefined,
    theme: "light",
}

export default function ForgotPassword() {
    const [loading, setLoading] = useState(false);

    const {
        handleSubmit,
        control,
        setValue,
        register,
        getValues,
        reset,
        setError,
        formState: { errors },
      } = useForm({
        resolver: yupResolver(schema),
    });

    const onSubmit = async (data: any) => {
        setLoading(true);
        try {
          const response = await axiosPublic.post(api_routes.forgot_password, {...data});
          toast.success(response.data.message, toastConfig);            
          reset({
            email: "",
          });
        } catch (error: any) {
          console.log(error);
          if (error?.response?.data?.message) {
            toast.error(error?.response?.data?.message, toastConfig);
          }
          if (error?.response?.data?.errors?.email) {
            setError("email", {
              type: "server",
              message: error?.response?.data?.errors?.email[0],
            });
          }
        } finally {
          setLoading(false);
        }
      };

    return (
        <>
            <Head>
                <title>Detox-Folks</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/favicon.png" />
            </Head>
            <section className="user-form-part">
                <div className="container">
                    <div className="row justify-content-center">
                        <div className="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5">
                            <div className="user-form-card">
                                <div className="user-form-title">
                                    <h2>worried?</h2>
                                    <p>No Problem! Just Follow The Simple Way</p>
                                </div>
                                <form className="user-form" onSubmit={handleSubmit(onSubmit)}>
                                    <div className="form-group">
                                        <input
                                            type="email"
                                            className="form-control"
                                            placeholder="Enter your email"
                                            {...register('email')}
                                        />
                                        <ErrorMessage
                                            errors={errors}
                                            name='email'
                                            as={<div style={{ color: 'red' }} />}
                                        />
                                    </div>
                                    <div className="form-button">
                                        <button type="submit" disabled={loading}>
                                          {
                                            loading ? <Spinner/> : <>
                                              send reset link
                                            </>
                                          }
                                        </button>
                                    </div>
                                </form>
                            </div>
                            <div className="user-form-remind mb-5">
                                <p>Go Back To<Link href="/login">login here</Link></p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
