import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


export default function ForgotPassword() {
  return (
    <>
        <Head>
            <title>Detox-Folks</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/images/favicon.png" />
        </Head>
        <section className="user-form-part">
            <div className="container">
                <div className="row justify-content-center">
                <div className="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5">
                    <div className="user-form-logo">
                    <Link href="/"><img src="/images/logo.png" alt="logo" /></Link>
                    </div>
                    <div className="user-form-card">
                    <div className="user-form-title">
                        <h2>worried?</h2>
                        <p>No Problem! Just Follow The Simple Way</p>
                    </div>
                    <form className="user-form">
                        <div className="form-group">
                        <input
                            type="email"
                            className="form-control"
                            placeholder="Enter your email"
                        />
                        </div>
                        <div className="form-button">
                        <button type="submit">get reset link</button>
                        </div>
                    </form>
                    </div>
                    <div className="user-form-remind">
                    <p>Go Back To<Link href="/login">login here</Link></p>
                    </div>
                    <div className="user-form-footer">
                    <p>Greeny | &COPY; Copyright by <a href="#">Detox-Folks</a></p>
                    </div>
                </div>
                </div>
            </div>
        </section>
    </>
  )
}
