import Head from 'next/head'
import Banner from '@/components/Banner';
import PartnerSlider from '@/components/PartnerSlider';
import TestimonialSlider from '@/components/TestimonialSlider';
import BlogSlider from '@/components/BlogSlider';
import AboutSection from '@/components/AboutSection';
import Link from 'next/link';
import type { InferGetServerSidePropsType, GetServerSideProps } from 'next'
import { axiosPublic } from '../../axios';
import { api_routes } from '@/helper/routes';
import { AboutSectionType, BannerType } from '@/helper/types';
import FeaturedProducts from '@/components/FeaturedProducts';
import SaleProducts from '@/components/SaleProducts';
import NewProducts from '@/components/NewProducts';

type ServerSideProps = {
  banner: BannerType[];
  about: AboutSectionType;
}

export const getServerSideProps: GetServerSideProps<{
  repo: ServerSideProps
}> = async () => {
  const bannerResponse = await axiosPublic.get(api_routes.home_page_banner);
  // const aboutResponse = await axiosPublic.get(api_routes.about_section);
  return { props: { repo: {
    banner: bannerResponse.data.banner,
    // about: aboutResponse.data.about,
    // banner: [],
    about: {
      id: 0,
      slug: '',
      description: '',
      heading: '',
      description_unfiltered: '',
      image: '',
      created_at: '',
      updated_at: '',
    },
  } } }
}

export default function Home({
  repo,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>DetoxFolks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
    <Banner banner={repo.banner} />
    {/* <AboutSection  {...repo.about} /> */}

    <FeaturedProducts />

    <NewProducts />

    <SaleProducts />
    
    <PartnerSlider />
    <TestimonialSlider />
    <BlogSlider />
    </>
  )
}
