import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


export default function Login() {
  return (
    <>
        <Head>
            <title>Detox-Folks</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/images/favicon.png" />
        </Head>
        <section className="user-form-part">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5">
            <div className="user-form-logo">
              <Link href="/"><img src="/images/logo.png" alt="logo" /></Link>
            </div>
            <div className="user-form-card">
              <div className="user-form-title">
                <h2>welcome!</h2>
                <p>Use your credentials to access</p>
              </div>
              <div className="user-form-group">
                <form className="user-form">
                  <div className="form-group">
                    <input
                      type="email"
                      className="form-control"
                      placeholder="Enter your email"
                    />
                  </div>
                  <div className="form-group">
                    <input
                      type="password"
                      className="form-control"
                      placeholder="Enter your password"
                    />
                  </div>
                  <div className="form-check mb-3">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      value=""
                      id="check"
                    /><label className="form-check-label" htmlFor="check"
                      >Remember Me</label
                    >
                  </div>
                  <div className="form-button">
                    <button type="submit">login</button>
                    <p>
                      Forgot your password?<Link href="/forgot-password"
                        >reset here</Link
                      >
                    </p>
                  </div>
                </form>
              </div>
            </div>
            <div className="user-form-remind">
              <p>
                Don&apos;t have any account?<Link href="/register">register here</Link>
              </p>
            </div>
            <div className="user-form-footer">
              <p>Greeny | &COPY; Copyright by <a href="#">Detox-Folks</a></p>
            </div>
          </div>
        </div>
      </div>
    </section>
    </>
  )
}
