import Head from 'next/head'
import LoginModal from '@/components/LoginModal';


export default function Login() {

  return (
    <>
        <Head>
            <title>DetoxFolks</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/images/favicon.png" />
        </Head>
        <section className="user-form-part">
          <div className="container">
            <div className="row justify-content-center">
                  <div className="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 mb-5">
                    <LoginModal />
                  </div>
            </div>
          </div>
        </section>
    </>
  )
}
