import Head from 'next/head'
import Hero from '@/components/Hero';
import { useSession } from 'next-auth/react';

export default function Profile() {
  const { status, data } = useSession();
  console.log(data)

  return (
    <>
      <Head>
        <title>DetoxFolks - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Hero name='Profile' />

      <section className="inner-section profile-part">
        <div className="container">
          <div className="row">
            <div className="col-lg-12">
              <div className="account-card">
                <div className="account-title">
                  <h4>Your Profile</h4>
                </div>
                <div className="account-content">
                  <div className="row">
                    <div className="col-md-6 col-lg-3">
                      <div className="form-group">
                        <label className="form-label">name</label
                        ><input
                          className="form-control"
                          type="text"
                          defaultValue="Miron Mahmud"
                        />
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-3">
                      <div className="form-group">
                        <label className="form-label">Email</label
                        ><input
                          className="form-control"
                          type="email"
                          defaultValue="mironcoder@gmail.com"
                        />
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-3">
                      <div className="form-group">
                        <label className="form-label">Phone</label
                        ><input
                          className="form-control"
                          type="text"
                          defaultValue="7892156160"
                        />
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-3">
                      <div className="profile-btn">
                        <a href="change-password.html">Update Profile</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-lg-12">
              <div className="account-card">
                <div className="account-title">
                  <h4>Password Setting</h4>
                </div>
                <div className="account-content">
                  <div className="row">
                    <div className="col-md-6 col-lg-3">
                      <div className="form-group">
                        <label className="form-label">Current Password</label
                        ><input
                          className="form-control"
                          type="password"
                          defaultValue="Miron Mahmud"
                        />
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-3">
                      <div className="form-group">
                        <label className="form-label">New Password</label
                        ><input
                          className="form-control"
                          type="password"
                          defaultValue="mironcoder@gmail.com"
                        />
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-3">
                      <div className="form-group">
                        <label className="form-label">Confirm Password</label
                        ><input
                          className="form-control"
                          type="password"
                          defaultValue="7892156160"
                        />
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-3">
                      <div className="profile-btn">
                        <a href="change-password.html">Update Password</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-lg-12">
              <div className="account-card">
                <div className="account-title">
                  <h4>delivery address</h4>
                  <button data-bs-toggle="modal" data-bs-target="#address-add">
                    add address
                  </button>
                </div>
                <div className="account-content">
                  <div className="row">
                    <div className="col-md-6 col-lg-4 alert fade show">
                      <div className="profile-card address active">
                        <h6>Home</h6>
                        <p>
                          jalkuri, fatullah, narayanganj-1420. word no-09, road
                          no-17/A
                        </p>
                        <ul className="user-action">
                          <li>
                            <button
                              className="edit icofont-edit"
                              title="Edit This"
                              data-bs-toggle="modal"
                              data-bs-target="#address-edit"
                            ></button>
                          </li>
                          <li>
                            <button
                              className="trash icofont-ui-delete"
                              title="Remove This"
                              data-bs-dismiss="alert"
                            ></button>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-4 alert fade show">
                      <div className="profile-card address">
                        <h6>Office</h6>
                        <p>
                          east tejturi bazar, dhaka-1200. word no-04, road
                          no-13/c, house no-4/b
                        </p>
                        <ul className="user-action">
                          <li>
                            <button
                              className="edit icofont-edit"
                              title="Edit This"
                              data-bs-toggle="modal"
                              data-bs-target="#address-edit"
                            ></button>
                          </li>
                          <li>
                            <button
                              className="trash icofont-ui-delete"
                              title="Remove This"
                              data-bs-dismiss="alert"
                            ></button>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-4 alert fade show">
                      <div className="profile-card address">
                        <h6>Bussiness</h6>
                        <p>
                          kawran bazar, dhaka-1100. word no-02, road no-13/d,
                          house no-7/m
                        </p>
                        <ul className="user-action">
                          <li>
                            <button
                              className="edit icofont-edit"
                              title="Edit This"
                              data-bs-toggle="modal"
                              data-bs-target="#address-edit"
                            ></button>
                          </li>
                          <li>
                            <button
                              className="trash icofont-ui-delete"
                              title="Remove This"
                              data-bs-dismiss="alert"
                            ></button>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="modal fade" id="address-add">
        <div className="modal-dialog modal-dialog-centered">
          <div className="modal-content">
            <button className="modal-close" data-bs-dismiss="modal">
              <i className="icofont-close"></i>
            </button>
            <form className="modal-form">
              <div className="form-title"><h3>add new address</h3></div>
              <div className="form-group">
                <label className="form-label">title</label
                ><select className="form-select">
                  <option selected>choose title</option>
                  <option value="home">home</option>
                  <option value="office">office</option>
                  <option value="Bussiness">Bussiness</option>
                  <option value="academy">academy</option>
                  <option value="others">others</option>
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">address</label
                ><textarea
                  className="form-control"
                  placeholder="Enter your address"
                ></textarea>
              </div>
              <button className="form-btn" type="submit">save address info</button>
            </form>
          </div>
        </div>
      </div>
      <div className="modal fade" id="address-edit">
        <div className="modal-dialog modal-dialog-centered">
          <div className="modal-content">
            <button className="modal-close" data-bs-dismiss="modal">
              <i className="icofont-close"></i>
            </button>
            <form className="modal-form">
              <div className="form-title"><h3>edit address info</h3></div>
              <div className="form-group">
                <label className="form-label">title</label
                ><select className="form-select">
                  <option value="home" selected>home</option>
                  <option value="office">office</option>
                  <option value="Bussiness">Bussiness</option>
                  <option value="academy">academy</option>
                  <option value="others">others</option>
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">address</label
                ><textarea
                  className="form-control"
                  placeholder="jalkuri, fatullah, narayanganj-1420. word no-09, road no-17/A"
                ></textarea>
              </div>
              <button className="form-btn" type="submit">save address info</button>
            </form>
          </div>
        </div>
      </div>

    </>
  )
}
