import Head from 'next/head'
import Hero from '@/components/Hero';
import ProfileCard from '@/components/ProfileCard';
import PasswordCard from '@/components/PasswordCard';
import BillingAddress from '@/components/BillingAddress';
import BillingInformation from '@/components/BillingInformation';

export default function Profile() {

  return (
    <>
      <Head>
        <title>DetoxFolks - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Hero name='Profile' />

      <section className="inner-section profile-part">
        <div className="container">
          <div className="row">
            <div className="col-lg-12">
              <ProfileCard />
            </div>
            <div className="col-lg-12">
              <PasswordCard />
            </div>
            <div className="col-lg-12">
              <BillingInformation />
            </div>
            <div className="col-lg-12">
              <BillingAddress />
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
