import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


export default function Register() {
  return (
    <>
      <Head>
        <title>Detox-Folks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <section className="user-form-part">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5">
              <div className="user-form-card">
                <div className="user-form-title">
                  <h2>Join Now!</h2>
                  <p>Setup A New Account In A Minute</p>
                </div>
                <div className="user-form-group">
                  <form className="user-form">
                    <div className="form-group">
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Enter your name"
                      />
                    </div>
                    <div className="form-group">
                      <input
                        type="email"
                        className="form-control"
                        placeholder="Enter your email"
                      />
                    </div>
                    <div className="form-group">
                      <input
                        type="password"
                        className="form-control"
                        placeholder="Enter your password"
                      />
                    </div>
                    <div className="form-group">
                      <input
                        type="password"
                        className="form-control"
                        placeholder="Enter repeat password"
                      />
                    </div>
                    <div className="form-check mb-3">
                      <input
                        className="form-check-input"
                        type="checkbox"
                        defaultValue=""
                        id="check"
                      /><label className="form-check-label" htmlFor="check"
                      >Accept all the <a href="#">Terms & Conditions</a></label
                      >
                    </div>
                    <div className="form-button">
                      <button type="submit">register</button>
                    </div>
                  </form>
                </div>
              </div>
              <div className="user-form-remind mb-5">
                <p>Already Have An Account?<Link href="/login">login here</Link></p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
