import Head from 'next/head'
import Hero from '@/components/Hero';
import Layout from '@/components/Layout';


export default function Wishlist() {
  return (
    <Layout>
      <Head>
        <title>Detox-Folks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Hero name='Wishlist' />

      <section className="inner-section wishlist-part">
        <div className="container">
          <div className="row">
            <div className="col-lg-12">
              <div className="table-scroll">
                <table className="table-list">
                  <thead>
                    <tr>
                      <th scope="col">Serial</th>
                      <th scope="col">Product</th>
                      <th scope="col">Name</th>
                      <th scope="col">Price</th>
                      <th scope="col">description</th>
                      <th scope="col">status</th>
                      <th scope="col">shopping</th>
                      <th scope="col">action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className="table-serial"><h6>01</h6></td>
                      <td className="table-image">
                        <img src="https://static.vecteezy.com/system/resources/previews/016/694/735/original/tissue-with-transparent-background-png.png" alt="product" />
                      </td>
                      <td className="table-name"><h6>product name</h6></td>
                      <td className="table-price">
                        <h6>$19<small>/kilo</small></h6>
                      </td>
                      <td className="table-desc">
                        <p>
                          Lorem ipsum nobis eaque excepturi nisi eveniet...<a
                            href="product-video.html"
                          >read more</a
                          >
                        </p>
                      </td>
                      <td className="table-status">
                        <h6 className="stock-out">stock out</h6>
                      </td>
                      <td className="table-shop">
                        <button className="product-add" title="Add to Cart">
                          add to cart
                        </button>
                        <div className="product-action">
                          <button className="action-minus" title="Quantity Minus">
                            <i className="icofont-minus"></i></button
                          ><input
                            className="action-input"
                            title="Quantity Number"
                            type="text"
                            name="quantity"
                            defaultValue="1"
                          /><button className="action-plus" title="Quantity Plus">
                            <i className="icofont-plus"></i>
                          </button>
                        </div>
                      </td>
                      <td className="table-action">
                        <a
                          className="view"
                          href="#"
                          title="Quick View"
                          data-bs-toggle="modal"
                          data-bs-target="#product-view"
                        ><i className="fas fa-eye"></i></a
                        ><a className="trash" href="#" title="Remove Wishlist"
                        ><i className="icofont-trash"></i
                        ></a>
                      </td>
                    </tr>
                    <tr>
                      <td className="table-serial"><h6>02</h6></td>
                      <td className="table-image">
                        <img src="https://m.media-amazon.com/images/I/51pILIz20gL._SL1200_.jpg" alt="product" />
                      </td>
                      <td className="table-name"><h6>product name</h6></td>
                      <td className="table-price">
                        <h6>$78<small>/kilo</small></h6>
                      </td>
                      <td className="table-desc">
                        <p>
                          Lorem ipsum nobis eaque excepturi nisi eveniet...<a
                            href="product-video.html"
                          >read more</a
                          >
                        </p>
                      </td>
                      <td className="table-status">
                        <h6 className="stock-in">stock in</h6>
                      </td>
                      <td className="table-shop">
                        <button className="product-add" title="Add to Cart">
                          add to cart
                        </button>
                        <div className="product-action">
                          <button className="action-minus" title="Quantity Minus">
                            <i className="icofont-minus"></i></button
                          ><input
                            className="action-input"
                            title="Quantity Number"
                            type="text"
                            name="quantity"
                            defaultValue="1"
                          /><button className="action-plus" title="Quantity Plus">
                            <i className="icofont-plus"></i>
                          </button>
                        </div>
                      </td>
                      <td className="table-action">
                        <a
                          className="view"
                          href="#"
                          title="Quick View"
                          data-bs-toggle="modal"
                          data-bs-target="#product-view"
                        ><i className="fas fa-eye"></i></a
                        ><a className="trash" href="#" title="Remove Wishlist"
                        ><i className="icofont-trash"></i
                        ></a>
                      </td>
                    </tr>
                    <tr>
                      <td className="table-serial"><h6>03</h6></td>
                      <td className="table-image">
                        <img src="https://img.freepik.com/premium-photo/toothpicks-box-isolated-white_179068-1760.jpg?w=2000" alt="product" />
                      </td>
                      <td className="table-name"><h6>product name</h6></td>
                      <td className="table-price">
                        <h6>$68<small>/kilo</small></h6>
                      </td>
                      <td className="table-desc">
                        <p>
                          Lorem ipsum nobis eaque excepturi nisi eveniet...<a
                            href="product-video.html"
                          >read more</a
                          >
                        </p>
                      </td>
                      <td className="table-status">
                        <h6 className="stock-out">stock out</h6>
                      </td>
                      <td className="table-shop">
                        <button className="product-add" title="Add to Cart">
                          add to cart
                        </button>
                        <div className="product-action">
                          <button className="action-minus" title="Quantity Minus">
                            <i className="icofont-minus"></i></button
                          ><input
                            className="action-input"
                            title="Quantity Number"
                            type="text"
                            name="quantity"
                            defaultValue="1"
                          /><button className="action-plus" title="Quantity Plus">
                            <i className="icofont-plus"></i>
                          </button>
                        </div>
                      </td>
                      <td className="table-action">
                        <a
                          className="view"
                          href="#"
                          title="Quick View"
                          data-bs-toggle="modal"
                          data-bs-target="#product-view"
                        ><i className="fas fa-eye"></i></a
                        ><a className="trash" href="#" title="Remove Wishlist"
                        ><i className="icofont-trash"></i
                        ></a>
                      </td>
                    </tr>
                    <tr>
                      <td className="table-serial"><h6>04</h6></td>
                      <td className="table-image">
                        <img src="https://3.imimg.com/data3/RY/JL/MY-11348186/aluminium-foil-pouch-1000x1000.jpg" alt="product" />
                      </td>
                      <td className="table-name"><h6>product name</h6></td>
                      <td className="table-price">
                        <h6>$24<small>/kilo</small></h6>
                      </td>
                      <td className="table-desc">
                        <p>
                          Lorem ipsum nobis eaque excepturi nisi eveniet...<a
                            href="product-video.html"
                          >read more</a
                          >
                        </p>
                      </td>
                      <td className="table-status">
                        <h6 className="stock-in">stock in</h6>
                      </td>
                      <td className="table-shop">
                        <button className="product-add" title="Add to Cart">
                          add to cart
                        </button>
                        <div className="product-action">
                          <button className="action-minus" title="Quantity Minus">
                            <i className="icofont-minus"></i></button
                          ><input
                            className="action-input"
                            title="Quantity Number"
                            type="text"
                            name="quantity"
                            defaultValue="1"
                          /><button className="action-plus" title="Quantity Plus">
                            <i className="icofont-plus"></i>
                          </button>
                        </div>
                      </td>
                      <td className="table-action">
                        <a
                          className="view"
                          href="#"
                          title="Quick View"
                          data-bs-toggle="modal"
                          data-bs-target="#product-view"
                        ><i className="fas fa-eye"></i></a
                        ><a className="trash" href="#" title="Remove Wishlist"
                        ><i className="icofont-trash"></i
                        ></a>
                      </td>
                    </tr>
                    <tr>
                      <td className="table-serial"><h6>05</h6></td>
                      <td className="table-image">
                        <img src="https://5.imimg.com/data5/ANDROID/Default/2022/11/NH/SS/MO/4041306/product-jpeg-500x500.jpg" alt="product" />
                      </td>
                      <td className="table-name"><h6>product name</h6></td>
                      <td className="table-price">
                        <h6>$34<small>/kilo</small></h6>
                      </td>
                      <td className="table-desc">
                        <p>
                          Lorem ipsum nobis eaque excepturi nisi eveniet...<a
                            href="product-video.html"
                          >read more</a
                          >
                        </p>
                      </td>
                      <td className="table-status">
                        <h6 className="stock-out">stock out</h6>
                      </td>
                      <td className="table-shop">
                        <button className="product-add" title="Add to Cart">
                          add to cart
                        </button>
                        <div className="product-action">
                          <button className="action-minus" title="Quantity Minus">
                            <i className="icofont-minus"></i></button
                          ><input
                            className="action-input"
                            title="Quantity Number"
                            type="text"
                            name="quantity"
                            defaultValue="1"
                          /><button className="action-plus" title="Quantity Plus">
                            <i className="icofont-plus"></i>
                          </button>
                        </div>
                      </td>
                      <td className="table-action">
                        <a
                          className="view"
                          href="#"
                          title="Quick View"
                          data-bs-toggle="modal"
                          data-bs-target="#product-view"
                        ><i className="fas fa-eye"></i></a
                        ><a className="trash" href="#" title="Remove Wishlist"
                        ><i className="icofont-trash"></i
                        ></a>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </section>

    </Layout>
  )
}
