import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Hero from '@/components/Hero';


export default function Contact() {
  return (
    <>
      <Head>
        <title>Detox-Folks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Header />
      <Hero name='Blog Detail' />

      <section className="inner-section blog-details-part">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8 col-xl-8">
              <article className="blog-details">
                <a className="blog-details-thumb w-100" href="#"
                ><img src="/images/blog/01.jpg" alt="blog"
                  /></a>
                <div className="blog-details-content">
                  <ul className="blog-details-meta">
                    <li>
                      <i className="icofont-ui-calendar"></i
                      ><span>february 02, 2021</span>
                    </li>
                    <li>
                      <i className="icofont-user-alt-3"></i><span>Miron mahmud</span>
                    </li>
                    <li>
                      <i className="icofont-speech-comments"></i
                      ><span>25 comments</span>
                    </li>
                    <li>
                      <i className="icofont-share-boxed"></i><span>34 share</span>
                    </li>
                  </ul>
                  <h2 className="blog-details-title">
                    Adipisicing elit. Earum beatae, eius voluptates lorem ipsum
                    dolor sit amet consectetur.
                  </h2>
                  <p className="blog-details-desc">
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                    Molestias repellendus laudantium at optio ex, magnam illo
                    ducimus placeat voluptates officiis molestiae ratione
                    assumenda dignissimos est id hic veritatis. Aspernatur aliquam
                    praesentium officiis pariatur velit nesciunt debitis odio,
                    dolores harum, quidem nobis enim. Incidunt quia doloremque
                    ipsam optio repudiandae non ipsa.
                  </p>
                  <p className="blog-details-desc">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                    Voluptas est nisi ut eius quod? Libero, labore. Omnis maiores
                    at, incidunt odit commodi, possimus voluptas porro sunt beatae
                    laboriosam provident. Id, sit laborum accusantium quia ad aut
                    eaque obcaecati eos, <a href="#">adipisci</a>molestias quasi
                    nostrum harum nihil, rerum totam doloribus perspiciatis quos
                    reiciendis voluptatibus. Eos numquam eaque sed nemo illo optio
                    quos facere, at alias! Doloremque nemo, porro neque magnam
                    voluptatem harum at quidem. Porro asperiores facere veritatis
                    consequatur. Minus amet error nam laudantium omnis modi
                    molestias, ex eveniet sed non. Veniam quas aspernatur quisquam
                    aut quis ea iusto, officia eos sunt vel, voluptatibus incidunt
                    ut eius nesciunt perspiciatis modi reiciendis fugit alias
                    autem, dolorum mollitia esse earum? Doloribus illum culpa
                    eligendi!
                  </p>
                  <blockquote className="blog-details-quote">
                    <p>
                      Adipisicing elit Qui ipsam natus aspernatur quaerat impedit
                      eveniet ipsum dolor
                    </p>
                    <footer>- ROSALINA PONG</footer>
                  </blockquote>
                  <p className="blog-details-desc">
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                    Rerum eligendi asperiores id, doloribus quasi assumenda
                    perspiciatis dicta vero quidem repellendus qui dolore et
                    recusandae deserunt at perferendis dignissimos provident,
                    similique quos dolor dolorem ducimus modi nisi quis? Hic
                    error, officia, porro officiis explicabo consequatur magnam
                    nostrum itaque minima expedita ex assumenda dolorum
                    consequuntur molestias, blanditiis dignissimos vel quia.
                    Aliquam neque, omnis culpa quaerat dolor quibusdam laborum
                    consequuntur tenetur sit excepturi adipisci, ducimus molestiae
                    exercitationem perspiciatis, nobis eum magnam explicabo.
                  </p>
                  <div className="row blog-details-grid">
                    <div className="col-md-6 col-lg-6">
                      <img
                        className="img-fluid"
                        src="/images/blog/02.jpg"
                        alt="blog"
                      />
                    </div>
                    <div className="col-md-6 col-lg-6">
                      <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Odit veniam quam natus! Dignissimos, sed. Sint enim
                        perferendis illum rem natus commodi dolorum, nobis,
                        temporibus minima dolores numquam ab nemo aspernatur
                        placeat vitae assumenda? Provident cumque aliquid
                        cupiditate nam libero vero praesentium tempora. Nostrum
                        vero ipsa soluta minus facilis doloremque quis.
                      </p>
                    </div>
                  </div>
                  <div className="blog-details-subtitle">
                    <h3>Lorem ipsum dolor sit amet consectetur</h3>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                      ullamco laboris nisi ut aliquip ex ea commodo consequat.
                      Duis aute irure dolor in reprehenderit in voluptate velit
                      esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                      occaecat cupidatat non proident, sunt in culpa qui officia.
                    </p>
                  </div>
                  <div className="blog-details-subtitle">
                    <h3>Aboris nisi ut aliquip commodo consequat</h3>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                      ullamco laboris nisi ut aliquip ex ea commodo consequat.
                      Duis aute irure dolor in reprehenderit in voluptate velit
                      esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                      occaecat cupidatat non proident, sunt in culpa qui officia.
                    </p>
                  </div>
                  <a className="blog-details-thumb mb-4" href="#"
                  ><img src="/images/blog/04.jpg" alt="blog"
                    /></a>
                  <ul className="blog-details-list">
                    <li>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Sequi error ex placeat repudiandae et ut modi non libero
                      mollitia velit. Dolor consequuntur quo error explicabo?
                      Officiis vitae sed officia autem harum sequi pariatur
                      corporis fugit suscipit? Laboriosam animi voluptatum
                      quibusdam voluptate expedita corrupti natus rerum, quaerat
                      velit, voluptates saepe quasi.
                    </li>
                    <li>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Sequi error ex placeat repudiandae et ut modi non libero
                      mollitia velit. Dolor consequuntur quo error explicabo?
                      Officiis vitae sed officia autem harum sequi pariatur
                      corporis fugit <a href="#">suscipit?</a>Laboriosam animi
                      voluptatum quibusdam voluptate expedita corrupti natus
                      rerum, quaerat velit, voluptates saepe quasi.
                    </li>
                    <li>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                      Sequi error ex placeat repudiandae et ut modi non libero
                      mollitia velit. Dolor consequuntur quo error explicabo?
                      Officiis vitae sed officia autem harum sequi pariatur
                      corporis fugit suscipit? Laboriosam animi voluptatum
                      quibusdam voluptate expedita corrupti natus rerum, quaerat
                      velit, voluptates saepe quasi.
                    </li>
                  </ul>
                  <div className="blog-details-footer">
                    <ul className="blog-details-share">
                      <li><span>share:</span></li>
                      <li><a href="#" className="icofont-facebook"></a></li>
                      <li><a href="#" className="icofont-twitter"></a></li>
                      <li><a href="#" className="icofont-linkedin"></a></li>
                      <li><a href="#" className="icofont-pinterest"></a></li>
                      <li><a href="#" className="icofont-instagram"></a></li>
                    </ul>
                  </div>
                </div>
              </article>
              <div className="blog-details-navigate">
                <div className="row">
                  <div className="col-md-6 col-lg-6">
                    <div className="blog-details-prev">
                      <a className="nav-arrow" href="#"
                      ><i className="icofont-arrow-left"></i>prev post</a
                      >
                    </div>
                  </div>
                  <div className="col-md-6 col-lg-6">
                    <div className="blog-details-next">
                      <a className="nav-arrow" href="#"
                      >next post<i className="icofont-arrow-right"></i
                      ></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-xl-4 col-lg-4">
              <div className="blog-widget">
                <h3 className="blog-widget-title">Find blogs</h3>
                <form className="blog-widget-form">
                  <input type="text" placeholder="Search blogs" /><button
                    className="icofont-search-1"
                  ></button>
                </form>
              </div>
              <div className="blog-widget">
                <h3 className="blog-widget-title">popular feeds</h3>
                <ul className="blog-widget-feed">
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/01.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/02.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/03.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/04.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/05.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                </ul>
              </div>
              <div className="blog-widget">
                <h3 className="blog-widget-title">follow us</h3>
                <ul className="blog-widget-social">
                  <li><a href="#" className="icofont-facebook"></a></li>
                  <li><a href="#" className="icofont-twitter"></a></li>
                  <li><a href="#" className="icofont-linkedin"></a></li>
                  <li><a href="#" className="icofont-pinterest"></a></li>
                  <li><a href="#" className="icofont-instagram"></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}
