import Head from 'next/head'
import Hero from '@/components/Hero';
import useSWR from 'swr'
import { api_routes } from "@/helper/routes";
import { BlogResponseType } from "@/helper/types";
import BlogCard from '@/components/BlogCard';
import Layout from '@/components/Layout';

const loadingArr = [1, 2, 3, 4]

export default function Blogs() {

  const { data, isLoading } = useSWR<BlogResponseType>(api_routes.blog + '?total=8');

  return (
    <Layout>
      <Head>
        <title>DetoxFolks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Hero name='Blogs' />

      <section className="inner-section blog-grid">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <div className="row">
                <div className="col-lg-12">
                  <div className="top-filter">
                    <div className="filter-show">
                      <label className="filter-label">Show :</label
                      ><select className="form-select filter-select">
                        <option value="1">12</option>
                        <option value="2">24</option>
                        <option value="3">36</option>
                      </select>
                    </div>
                    <div className="filter-short">
                      <label className="filter-label">Sort by :</label
                      ><select className="form-select filter-select">
                        <option selected>default</option>
                        <option value="3">recent</option>
                        <option value="1">featured</option>
                        <option value="2">recommend</option>
                      </select>
                    </div>
                  </div>
                </div>
              </div>
              <div className="row">
                {
                  isLoading && loadingArr.map( i => <div className="col-md-6 col-lg-6" key={i}>
                  <div className="blog-img-loading"></div>
                  <div className="blog-heading-loading"></div>
                  <div className="blog-paragraph-loading"></div>
                </div>)
                }
                {
                  data?.data.map((item, i) => <div className="col-md-6 col-lg-6" key={i}>
                    <BlogCard {...item} />
                  </div>)
                }
              </div>
              <div className="row">
                <div className="col-lg-12">
                  <div className="bottom-paginate">
                    <p className="page-info">Showing 12 of 60 Results</p>
                    <ul className="pagination">
                      <li className="page-item">
                        <a className="page-link" href="#"
                        ><i className="fas fa-long-arrow-alt-left"></i
                        ></a>
                      </li>
                      <li className="page-item">
                        <a className="page-link active" href="#">1</a>
                      </li>
                      <li className="page-item">
                        <a className="page-link" href="#">2</a>
                      </li>
                      <li className="page-item">
                        <a className="page-link" href="#">3</a>
                      </li>
                      <li className="page-item">...</li>
                      <li className="page-item">
                        <a className="page-link" href="#">60</a>
                      </li>
                      <li className="page-item">
                        <a className="page-link" href="#"
                        ><i className="fas fa-long-arrow-alt-right"></i
                        ></a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-7 col-lg-4">
              <div className="blog-widget">
                <h3 className="blog-widget-title">Find blogs</h3>
                <form className="blog-widget-form">
                  <input type="text" placeholder="Search blogs" /><button
                    className="icofont-search-1"
                  ></button>
                </form>
              </div>
              <div className="blog-widget">
                <h3 className="blog-widget-title">popular feeds</h3>
                <ul className="blog-widget-feed">
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/01.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/02.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/03.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/04.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/05.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                </ul>
              </div>
              <div className="blog-widget">
                <h3 className="blog-widget-title">follow us</h3>
                <ul className="blog-widget-social">
                  <li><a href="#" className="icofont-facebook"></a></li>
                  <li><a href="#" className="icofont-twitter"></a></li>
                  <li><a href="#" className="icofont-linkedin"></a></li>
                  <li><a href="#" className="icofont-pinterest"></a></li>
                  <li><a href="#" className="icofont-instagram"></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
    </Layout>
  )
}
