import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Hero from '@/components/Hero';
import Link from 'next/link';


export default function Blogs() {
  return (
    <>
      <Head>
        <title>Detox-Folks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <Header />
      <Hero name='Blogs' />

      <section className="inner-section blog-grid">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-8">
              <div className="row">
                <div className="col-lg-12">
                  <div className="top-filter">
                    <div className="filter-show">
                      <label className="filter-label">Show :</label
                      ><select className="form-select filter-select">
                        <option value="1">12</option>
                        <option value="2">24</option>
                        <option value="3">36</option>
                      </select>
                    </div>
                    <div className="filter-short">
                      <label className="filter-label">Sort by :</label
                      ><select className="form-select filter-select">
                        <option selected>default</option>
                        <option value="3">recent</option>
                        <option value="1">featured</option>
                        <option value="2">recommend</option>
                      </select>
                    </div>
                  </div>
                </div>
              </div>
              <div className="row">
                <div className="col-md-6 col-lg-6">
                  <div className="blog-card">
                    <div className="blog-media">
                      <Link className="blog-img" href="/blogs/test"
                      ><img src="/images/blog/01.jpg" alt="blog"
                        /></Link>
                    </div>
                    <div className="blog-content">
                      <ul className="blog-meta">
                        <li><i className="fas fa-user"></i><span>admin</span></li>
                        <li>
                          <i className="fas fa-calendar-alt"></i
                          ><span>february 02, 2021</span>
                        </li>
                      </ul>
                      <h4 className="blog-title">
                        <Link href="/blogs/test"
                        >Voluptate blanditiis provident Lorem ipsum dolor sit
                          amet</Link
                        >
                      </h4>
                      <p className="blog-desc">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        Alias autem recusandae deleniti nam dignissimos sequi ...
                      </p>
                      <Link className="blog-btn" href="/blogs/test"
                      ><span>read more</span><i className="icofont-arrow-right"></i
                      ></Link>
                    </div>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6">
                  <div className="blog-card">
                    <div className="blog-media">
                      <Link className="blog-img" href="/blogs/test"
                      ><img src="/images/blog/02.jpg" alt="blog"
                        /></Link>
                    </div>
                    <div className="blog-content">
                      <ul className="blog-meta">
                        <li><i className="fas fa-user"></i><span>admin</span></li>
                        <li>
                          <i className="fas fa-calendar-alt"></i
                          ><span>february 02, 2021</span>
                        </li>
                      </ul>
                      <h4 className="blog-title">
                        <Link href="/blogs/test"
                        >Voluptate blanditiis provident Lorem ipsum dolor sit
                          amet</Link
                        >
                      </h4>
                      <p className="blog-desc">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        Alias autem recusandae deleniti nam dignissimos sequi ...
                      </p>
                      <Link className="blog-btn" href="/blogs/test"
                      ><span>read more</span><i className="icofont-arrow-right"></i
                      ></Link>
                    </div>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6">
                  <div className="blog-card">
                    <div className="blog-media">
                      <Link className="blog-img" href="/blogs/test"
                      ><img src="/images/blog/03.jpg" alt="blog"
                        /></Link>
                    </div>
                    <div className="blog-content">
                      <ul className="blog-meta">
                        <li><i className="fas fa-user"></i><span>admin</span></li>
                        <li>
                          <i className="fas fa-calendar-alt"></i
                          ><span>february 02, 2021</span>
                        </li>
                      </ul>
                      <h4 className="blog-title">
                        <Link href="/blogs/test"
                        >Voluptate blanditiis provident Lorem ipsum dolor sit
                          amet</Link
                        >
                      </h4>
                      <p className="blog-desc">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        Alias autem recusandae deleniti nam dignissimos sequi ...
                      </p>
                      <Link className="blog-btn" href="/blogs/test"
                      ><span>read more</span><i className="icofont-arrow-right"></i
                      ></Link>
                    </div>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6">
                  <div className="blog-card">
                    <div className="blog-media">
                      <Link className="blog-img" href="/blogs/test"
                      ><img src="/images/blog/04.jpg" alt="blog"
                        /></Link>
                    </div>
                    <div className="blog-content">
                      <ul className="blog-meta">
                        <li><i className="fas fa-user"></i><span>admin</span></li>
                        <li>
                          <i className="fas fa-calendar-alt"></i
                          ><span>february 02, 2021</span>
                        </li>
                      </ul>
                      <h4 className="blog-title">
                        <Link href="/blogs/test"
                        >Voluptate blanditiis provident Lorem ipsum dolor sit
                          amet</Link
                        >
                      </h4>
                      <p className="blog-desc">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        Alias autem recusandae deleniti nam dignissimos sequi ...
                      </p>
                      <Link className="blog-btn" href="/blogs/test"
                      ><span>read more</span><i className="icofont-arrow-right"></i
                      ></Link>
                    </div>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6">
                  <div className="blog-card">
                    <div className="blog-media">
                      <Link className="blog-img" href="/blogs/test"
                      ><img src="/images/blog/05.jpg" alt="blog"
                        /></Link>
                    </div>
                    <div className="blog-content">
                      <ul className="blog-meta">
                        <li><i className="fas fa-user"></i><span>admin</span></li>
                        <li>
                          <i className="fas fa-calendar-alt"></i
                          ><span>february 02, 2021</span>
                        </li>
                      </ul>
                      <h4 className="blog-title">
                        <Link href="/blogs/test"
                        >Voluptate blanditiis provident Lorem ipsum dolor sit
                          amet</Link
                        >
                      </h4>
                      <p className="blog-desc">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        Alias autem recusandae deleniti nam dignissimos sequi ...
                      </p>
                      <Link className="blog-btn" href="/blogs/test"
                      ><span>read more</span><i className="icofont-arrow-right"></i
                      ></Link>
                    </div>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6">
                  <div className="blog-card">
                    <div className="blog-media">
                      <Link className="blog-img" href="/blogs/test"
                      ><img src="/images/blog/06.jpg" alt="blog"
                        /></Link>
                    </div>
                    <div className="blog-content">
                      <ul className="blog-meta">
                        <li><i className="fas fa-user"></i><span>admin</span></li>
                        <li>
                          <i className="fas fa-calendar-alt"></i
                          ><span>february 02, 2021</span>
                        </li>
                      </ul>
                      <h4 className="blog-title">
                        <Link href="/blogs/test"
                        >Voluptate blanditiis provident Lorem ipsum dolor sit
                          amet</Link
                        >
                      </h4>
                      <p className="blog-desc">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        Alias autem recusandae deleniti nam dignissimos sequi ...
                      </p>
                      <Link className="blog-btn" href="/blogs/test"
                      ><span>read more</span><i className="icofont-arrow-right"></i
                      ></Link>
                    </div>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6">
                  <div className="blog-card">
                    <div className="blog-media">
                      <Link className="blog-img" href="/blogs/test"
                      ><img src="/images/blog/07.jpg" alt="blog"
                        /></Link>
                    </div>
                    <div className="blog-content">
                      <ul className="blog-meta">
                        <li><i className="fas fa-user"></i><span>admin</span></li>
                        <li>
                          <i className="fas fa-calendar-alt"></i
                          ><span>february 02, 2021</span>
                        </li>
                      </ul>
                      <h4 className="blog-title">
                        <Link href="/blogs/test"
                        >Voluptate blanditiis provident Lorem ipsum dolor sit
                          amet</Link
                        >
                      </h4>
                      <p className="blog-desc">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        Alias autem recusandae deleniti nam dignissimos sequi ...
                      </p>
                      <Link className="blog-btn" href="/blogs/test"
                      ><span>read more</span><i className="icofont-arrow-right"></i
                      ></Link>
                    </div>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6">
                  <div className="blog-card">
                    <div className="blog-media">
                      <Link className="blog-img" href="/blogs/test"
                      ><img src="/images/blog/08.jpg" alt="blog"
                        /></Link>
                    </div>
                    <div className="blog-content">
                      <ul className="blog-meta">
                        <li><i className="fas fa-user"></i><span>admin</span></li>
                        <li>
                          <i className="fas fa-calendar-alt"></i
                          ><span>february 02, 2021</span>
                        </li>
                      </ul>
                      <h4 className="blog-title">
                        <Link href="/blogs/test"
                        >Voluptate blanditiis provident Lorem ipsum dolor sit
                          amet</Link
                        >
                      </h4>
                      <p className="blog-desc">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                        Alias autem recusandae deleniti nam dignissimos sequi ...
                      </p>
                      <Link className="blog-btn" href="/blogs/test"
                      ><span>read more</span><i className="icofont-arrow-right"></i
                      ></Link>
                    </div>
                  </div>
                </div>
              </div>
              <div className="row">
                <div className="col-lg-12">
                  <div className="bottom-paginate">
                    <p className="page-info">Showing 12 of 60 Results</p>
                    <ul className="pagination">
                      <li className="page-item">
                        <a className="page-link" href="#"
                        ><i className="fas fa-long-arrow-alt-left"></i
                        ></a>
                      </li>
                      <li className="page-item">
                        <a className="page-link active" href="#">1</a>
                      </li>
                      <li className="page-item">
                        <a className="page-link" href="#">2</a>
                      </li>
                      <li className="page-item">
                        <a className="page-link" href="#">3</a>
                      </li>
                      <li className="page-item">...</li>
                      <li className="page-item">
                        <a className="page-link" href="#">60</a>
                      </li>
                      <li className="page-item">
                        <a className="page-link" href="#"
                        ><i className="fas fa-long-arrow-alt-right"></i
                        ></a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-7 col-lg-4">
              <div className="blog-widget">
                <h3 className="blog-widget-title">Find blogs</h3>
                <form className="blog-widget-form">
                  <input type="text" placeholder="Search blogs" /><button
                    className="icofont-search-1"
                  ></button>
                </form>
              </div>
              <div className="blog-widget">
                <h3 className="blog-widget-title">popular feeds</h3>
                <ul className="blog-widget-feed">
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/01.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/02.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/03.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/04.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                  <li>
                    <a className="blog-widget-media" href="#"
                    ><img src="/images/blog-widget/05.jpg" alt="blog-widget"
                      /></a>
                    <h6 className="blog-widget-text">
                      <a href="#">Lorem ipsum dolor sit amet consectetur</a
                      ><span>february 02, 2021</span>
                    </h6>
                  </li>
                </ul>
              </div>
              <div className="blog-widget">
                <h3 className="blog-widget-title">follow us</h3>
                <ul className="blog-widget-social">
                  <li><a href="#" className="icofont-facebook"></a></li>
                  <li><a href="#" className="icofont-twitter"></a></li>
                  <li><a href="#" className="icofont-linkedin"></a></li>
                  <li><a href="#" className="icofont-pinterest"></a></li>
                  <li><a href="#" className="icofont-instagram"></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}
